pipeline {
    agent any
    parameters {
        choice(name: 'BUILD_TYPE', choices: ['debug', 'release'], description: 'Tipul de build pentru aplicatie.')
        booleanParam(name: 'RUN_TESTS', defaultValue: true, description: 'Daca sa rulam sau nu teste in momentul rularii.')
        string(name: 'APP_VERSION', defaultValue: '1.0', description: 'Versiunea aplicatiei')
    }
    stages {
        stage('Build') {
            steps {
                sh "echo '''Ai ales ${params.BUILD_TYPE} ca tipul build-ului.'''"
            }
        }
        stage('Test') {
            when {
                expression { params.RUN_TESTS }
            }
            steps {
                sh "echo '''Deoarece parametrul RUN_TEST este ${params.BUILD_TYPE} afisam acest mesaj.'''"
            }
        }
        stage('Deploy') {
            steps {
                sh "echo '''Facem deploy la aplicatie. Versiunea curenta este: ${params.APP_VERSION}'''"
            }
        }
    }
}